services:
  # Backend API Server
  - type: web
    name: unifest-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: unifest-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://unifest-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: unifest-frontend
    runtime: static
    plan: free
    region: oregon
    buildCommand: cd unifest-order-system && npm install && npm run build
    staticPublishPath: unifest-order-system/dist
    envVars:
      - key: VITE_API_URL
        value: https://unifest-backend.onrender.com

databases:
  - name: unifest-database
    plan: free
    databaseName: unifest_order_db
    user: unifest_user
    region: oregon
